version: 2
updates:
  - package-ecosystem: "cargo"  # Rust 的包管理器
    directory: "/"              # 配置文件所在目录（通常是根目录）
    schedule:
      interval: "daily"         # 检查频率（daily/weekly/monthly）
    open-pull-requests-limit: 5 # 同时打开的 PR 最大数量
    assignees:                 # （可选）指定负责人
      - "xsy420"
    labels:                    # （可选）自动添加标签
      - "dependencies"
      - "rust"
