name: Continuous Deployment

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

env:
  PROJECT_NAME: ${{ github.repository.name }}

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-22.04
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}

  publish-binaries:
    name: Publish binaries
    needs: generate-changelog
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - {
              NAME: linux-x64-glibc,
              OS: ubuntu-22.04,
              TOOLCHAIN: stable,
              TARGET: x86_64-unknown-linux-gnu,
            }
          - {
              NAME: linux-x64-musl,
              OS: ubuntu-22.04,
              TOOLCHAIN: stable,
              TARGET: x86_64-unknown-linux-musl,
            }
          - {
              NAME: linux-x86-glibc,
              OS: ubuntu-22.04,
              TOOLCHAIN: stable,
              TARGET: i686-unknown-linux-gnu,
            }
          - {
              NAME: linux-x86-musl,
              OS: ubuntu-22.04,
              TOOLCHAIN: stable,
              TARGET: i686-unknown-linux-musl,
            }
          - {
              NAME: linux-arm64-glibc,
              OS: ubuntu-22.04,
              TOOLCHAIN: stable,
              TARGET: aarch64-unknown-linux-gnu,
            }
          - {
              NAME: linux-arm64-musl,
              OS: ubuntu-22.04,
              TOOLCHAIN: stable,
              TARGET: aarch64-unknown-linux-musl,
            }
          - {
              NAME: win32-x64-mingw,
              OS: windows-2022,
              TOOLCHAIN: stable,
              TARGET: x86_64-pc-windows-gnu,
            }
          - {
              NAME: win32-x64-msvc,
              OS: windows-2022,
              TOOLCHAIN: stable,
              TARGET: x86_64-pc-windows-msvc,
            }
          - {
              NAME: win32-x86-msvc,
              OS: windows-2022,
              TOOLCHAIN: stable,
              TARGET: i686-pc-windows-msvc,
            }
          - {
              NAME: win32-arm64-msvc,
              OS: windows-2022,
              TOOLCHAIN: stable,
              TARGET: aarch64-pc-windows-msvc,
            }
          - {
              NAME: darwin-x64,
              OS: macos-14,
              TOOLCHAIN: stable,
              TARGET: x86_64-apple-darwin,
            }
          - {
              NAME: darwin-arm64,
              OS: macos-14,
              TOOLCHAIN: stable,
              TARGET: aarch64-apple-darwin,
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Install dependencies
        shell: bash
        run: |
          if [[ "${{ matrix.build.NAME }}" = *"-musl" ]]; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends \
              --allow-unauthenticated musl-tools
          fi
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.build.TOOLCHAIN }}
          target: ${{ matrix.build.TARGET }}
          override: true
      - name: Build (linux/macos)
        if: matrix.build.OS != 'windows-2022'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --locked --target ${{ matrix.build.TARGET }}
      - name: Build (windows)
        if: matrix.build.OS == 'windows-2022'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.build.TARGET }}
      - name: Prepare release assets
        shell: bash
        run: |
          mkdir -p release/
          cp {LICENSE,README.md,CHANGELOG.md} release/
          for bin in '${{ env.PROJECT_NAME }}'; do
            if [ "${{ matrix.build.OS }}" = "windows-2022" ]; then
              bin="${bin}.exe"
            fi
            cp "target/${{ matrix.build.TARGET }}/release/${bin}" release/
          done
          mv release/ ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}/
      - name: Create release artifacts
        shell: bash
        run: |
          if [ "${{ matrix.build.OS }}" = "windows-2022" ]; then
            7z a -tzip "${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}.zip" \
              ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}/
          else
            tar -czvf ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}.tar.gz \
              ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}/
            shasum -a 512 ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}.tar.gz \
              > ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}.tar.gz.sha512
          fi
      - name: Sign the release
        if: matrix.build.OS == 'ubuntu-22.04' || matrix.build.OS == 'macos-14'
        run: |
          echo "${{ secrets.GPG_RELEASE_KEY }}" | base64 --decode > private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --import private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --detach-sign \
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}.tar.gz
      - name: Create additional release files
        shell: bash
        run: |
          tar -cf - ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}/ | xz -9 > ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --detach-sign \
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz
          shasum -a 512 ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz \
            > ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz.sha512
      - name: Publish to GitHub
        if: ${{ !contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}*
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz.sha512
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz.sig
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
      - name: Publish to GitHub (pre-release)
        if: ${{ contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}-${{ matrix.build.TARGET }}*
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz.sha512
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.tar.xz.sig
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          release_name: "Pre-release v${{ env.RELEASE_VERSION }}"
          prerelease: true

  publish-deb:
    name: Publish Debian package
    needs: generate-changelog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build Debian package
        run: |
          cargo build --release --locked -p ${{ env.PROJECT_NAME }}
          cargo-deb --deb-revision="" --strip -p ${{ env.PROJECT_NAME }} -v -o ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.deb
      - name: Sign the package
        run: |
          echo "${{ secrets.GPG_RELEASE_KEY }}" | base64 --decode > private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --import private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --detach-sign \
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.deb
      - name: Upload the release
        if: ${{ !contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.deb
          tag: ${{ github.ref }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
      - name: Upload the pre-release
        if: ${{ contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.deb
          tag: ${{ github.ref }}
          release_name: "Pre-release v${{ env.RELEASE_VERSION }}"
          prerelease: true

  publish-rpm:
    name: Publish RPM package
    needs: generate-changelog
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install cargo-generate-rpm
        run: cargo install cargo-generate-rpm
      - name: Build RPM package
        run: |
          cargo build --release --locked -p ${{ env.PROJECT_NAME }}
          cargo generate-rpm -p ${{ env.PROJECT_NAME }} -o ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.x86_64.rpm
      - name: Sign the package
        run: |
          echo "${{ secrets.GPG_RELEASE_KEY }}" | base64 --decode > private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --import private.key
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --pinentry-mode=loopback \
            --passphrase-fd 0 --detach-sign \
            ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.x86_64.rpm
      - name: Upload the release
        if: ${{ !contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.x86_64.rpm
          tag: ${{ github.ref }}
          release_name: "Release v${{ env.RELEASE_VERSION }}"
          body: "${{ needs.generate-changelog.outputs.release_body }}"
      - name: Upload the pre-release
        if: ${{ contains(github.ref, '-') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PROJECT_NAME }}-${{ env.RELEASE_VERSION }}.x86_64.rpm
          tag: ${{ github.ref }}
          release_name: "Pre-release v${{ env.RELEASE_VERSION }}"
          prerelease: true
