name: Cleanup PR Cache

permissions:
  contents: read
  actions: write  # 需要删除缓存的权限

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR cache
        uses: actions/github-script@v7
        with:
          script: |
            const { data: caches } = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
              key: `refs/pull/${context.payload.pull_request.number}/merge`
            });

            for (const cache of caches.actions_caches) {
              await github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id
              });
              console.log(`Deleted cache ${cache.key} (ID: ${cache.id})`);
            }
