name: Code Quality Checks

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  code_quality:
    uses: xsy420/meta/.github/workflows/code_quality.yml@main
