name: Rust

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/rust.yml'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/rust.yml'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  rust:
    uses: xsy420/meta/.github/workflows/rust.yml@main
